# Window (title, geometry)
window:
    title: taste-vizkit3d - body state visualization test
    x: 100
    y: 150

# 3D widget
widget:
    manipulator: TRACKBALL_MANIPULATOR

# Plugins
plugins:


    - type: RigidBodyStateVisualization
      name: amp
      modelPath: stim300.stl
      frame:
          base: world_osg
          position: [0, 0, 0]
          rotation: [1, 0, 0, 0]

    - type: RigidBodyStateVisualization
      name: arp
      modelPath: stim300.stl
      frame:
          base: world_osg
          position: [0, 0, 0]
          rotation: [1, 0, 0, 0]
          # rotation quaternion in order [w, x, y, z]

          #    - type: ModelVisualization
          #      modelPath: stim300.stl

    - type: GridVisualization
